In [1]:
import numpy as np
from itertools import combinations
import random 

In [2]:
def gen_board(N):
    board = np.identity(N, dtype="int").flatten()
    np.random.shuffle(board)
    return board.reshape(N,N)

In [3]:
board = gen_board(4)

In [4]:
print(board)

[[0 1 1 0]
 [0 0 1 0]
 [0 0 0 0]
 [0 0 0 1]]


In [5]:
def check_conflict(i1, j1, i2, j2, N):
    if i1 == i2 or j1 == j2:
        return 1

    for num in range(N):
        if i1 - num == i2 and j1 - num == j2:
            return 1
        if i1 + num == i2 and j1 + num == j2:
            return 1
        if i1 + num == i2 and j1 - num == j2:
            return 1
        if i1 - num == i2 and j1 + num == j2:
            return 1
    return 0

In [6]:
def calc_conflicts(board: np.ndarray):
    conflicts = 0
    queens = np.argwhere(board == 1)
    N = len(queens)

    for idx1, (i1, j1) in enumerate(queens):
        for idx2, (i2, j2) in enumerate(queens):
            if idx1 >= idx2:
                continue
            conflicts += check_conflict(i1, j1, i2, j2, N)
    return conflicts

In [7]:
calc_conflicts(board)

3

In [8]:
def gen_neighbors (board, n = 50):
    neighbour = [board]
    while len(neighbour) < n:
            neigh = board.copy()
            
            neigh_queens = list(map(tuple, np.argwhere(neigh == 1)))
            neigh_board = list(map(tuple, np.argwhere(neigh == 0)))

            queen = random.choice(neigh_queens)
            space = random.choice(neigh_board)

            neigh[queen] = 0
            neigh[space] = 1

            neighbour.append(neigh)
    return neighbour

In [9]:
def simple_NQueens(max_iter = 100):
    board = gen_board(8)
    iter = 0

    while calc_conflicts(board) > 0 and iter < max_iter:
        iter += 1
        neighbours = gen_neighbors(board)
        flag = True

        for neigh in neighbours: 
            if calc_conflicts(neigh) < calc_conflicts(board):
                board = neigh.copy()
                flag = False
                break
        else:
            break
            
    print(f"Iter stopped at {iter}")        
    print(f"Coflicts of board: {calc_conflicts(board)}")
    print(board)

In [10]:
simple_NQueens()

Iter stopped at 8
Coflicts of board: 4
[[0 0 0 0 1 0 0 1]
 [0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0 0]
 [1 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]]


In [11]:
def stochastic_NQueens(max_iter = 100):
    board = gen_board(8)
    iter = 0

    while calc_conflicts(board) > 0 and iter < max_iter:
        iter += 1
        neighbours = gen_neighbors(board)
        better_neigh = []

        for neigh in neighbours: 
            if calc_conflicts(neigh) <= calc_conflicts(board):
                better_neigh.append(neigh)

        if not better_neigh:
            break
            
        board = random.choice(better_neigh)
    
    print(f"Iter stopped at {iter}")        
    print(f"Coflicts of board: {calc_conflicts(board)}")
    print(board)

In [12]:
stochastic_NQueens()

Iter stopped at 100
Coflicts of board: 1
[[0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 1]
 [1 0 0 0 1 0 0 0]]


In [13]:
def steepest_NQueens(max_iter = 100):
    board = gen_board(8)
    iter = 0

    while calc_conflicts(board) > 0 and iter < max_iter:
        iter += 1
        neighbours = gen_neighbors(board)
        sol = board.copy()

        for neigh in neighbours: 
            if calc_conflicts(neigh) <= calc_conflicts(board):
                board = neigh.copy()

        if (sol == board).all():
            break

    print(f"Iter stopped at {iter}")        
    print(f"Coflicts of board: {calc_conflicts(board)}")
    print(board)

In [14]:
steepest_NQueens()

Iter stopped at 11
Coflicts of board: 1
[[0 0 0 0 0 1 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 0 0 1 0 1 0]
 [1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 1 0 0 0 0 0]]
